site_name: Filomena FORINA Projects Portfolio

repo_url: https://github.com/FloraFo/Python-Scripts/
edit_uri: blob/main/docs

site_description: "This website showcases my AI and ML projects, sharing knowledge and insights gained through development. It serves as a platform for future collaborations and connections in the fields of Artificial Intelligence and Machine Learning."
site_author: Filomena FORINA
nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Personal Expense Tracker: Projects/personalexpstracker.md
      - Preserving Heritage – Enhancing Tourism with AI: Projects/preservingheritage.md

theme:
  name: readthedocs
