site_name: Filomena FORINA Projects Portfolio
site_url: https://filomenaforina.com/ProjectsPortfolio/

repo_url: https://github.com/FloraFo/Python-Scripts/
edit_uri: blob/gh-pages/pgc_documentation/docs/

site_description: "This website showcases my AI and ML projects, sharing knowledge and insights gained through development. It serves as a platform for future collaborations and connections in the fields of Artificial Intelligence and Machine Learning."
site_author: Filomena FORINA
nav:
  - Home: index.md
  - About: about.md
  - Projects:
      - Personal Expense Traker: personalexpstraker.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - py
    - md
  color_mode: auto
  user_color_mode_toggle: True
  prev_next_buttons_location: none