site_name: Filomena FORINA Projects Portfolio
site_url: https://filomenaforina.com/ProjectsPortfolio/

repo_url: https://github.com/FloraFo/Python-Scripts

nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: True