name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12.4
      - run: pip install mkdocs
      - run: mkdocs gh-deploy --force
